### PR TITLE
Adjust the parallel settings

### PR DESCRIPTION
**Pull request by matinlotfali**
In this pull request, I am changing the `CPU_NUM` value back to `nproc` command which results the correct value of '4' in DC02, instead of the incorrect '12'

According to bitbake documentation [here](https://docs.yoctoproject.org/bitbake/2.4/bitbake-user-manual/bitbake-user-manual-ref-variables.html#term-BB_NUMBER_THREADS):
> The maximum number of tasks BitBake should run in parallel at any one time. If your host development system supports multiple cores, a good rule of thumb is to set this variable to twice the number of cores.

Therefore, I am multiplying `CPU_NUM` by 2 for `BB_NUMBER_THREADS`.

However, for `PARALLEL_MAKE` and every other parallel setting, the documentation says they all default to the number of cores. So no need to override them.

# The Good:

- This will cause the `bitbake` command with cache to complete around 10% faster.
- This will cause running multiple `bitbake` runs to add less pressure on the server.

### CODE REVIEW

**Review by mistyron — APPROVED** [review]
LGTM :+1: , looks good. It originally was this way but as mentioned, was modified because it wasn't working correctly on a contractor's system. Issue was however never fully/sufficiently investigated, I recall that the reported issue appeared on Windows 10 with WSL.

**Comment by matinlotfali** [comment]
> I recall that the reported issue appeared on Windows 10 with WSL.

I don't think the failure in the execution of this command is significant. We can change the script to ignore it if it fails like this:
```
(NUM_CPU=$(nproc) && echo "BB_NUMBER_THREADS = \"$((NUM_CPU*2))\"" >> ${LOCALCONF}) || :
```
What do you think?

**Comment by mistyron** [comment]
> > I recall that the reported issue appeared on Windows 10 with WSL.
> 
> I don't think the failure in the execution of this command is significant. We can change the script to ignore it if it fails like this:
> 
> ```
> (NUM_CPU=$(nproc) && echo "BB_NUMBER_THREADS = \"$((NUM_CPU*2))\"" >> ${LOCALCONF}) || :
> ```
> 
> What do you think?

Were you able to duplicate the problem? Mh, yes, ignore it.

**Comment by matinlotfali** [comment]
> Were you able to duplicate the problem?

It makes sense to get an error on WSL 1.

It is very common for WSL 1 to throw an error when a low-level command is executed. Microsoft tried to fix these errors one by one until they got tired and released WSL 2 which uses Hyper-V and a Linux kernel as opposed to their finicky translation layer.

**Pull request merged**
