### PR TITLE
Move out all kernel config fragments into meta-mistysom

### PR DESCRIPTION
**Pull request by matinlotfali**
This probably affects the other PR #13

### CODE REVIEW

**Review by mistyron — COMMENTED** [review]
@vlaltzic review changes here. There is a kernel config fragment file from you as well. Review and syn with @matinlotfali please

**Review by gfinlay — APPROVED** [review]
Approved.
Once this PR is merged, we will need to do a couple more things
1. Complete approval and merge of my PR #6 on rzv2l repo (https://github.com/MistySOM/rzv2l/pull/6/files).
2. Add same sort of changes to rzv2l as in this rzg2l PR #15 here to move out all mw_fragments from rzv2l repo, and then do a new PR for rzv2l to move mw_fragments.
Probably easier to do this as 2 separate PRs rather than combining into a single PR since my rzv2l PR #6 files have already been committed on the mistysom_io branch of rzv2l. Once PR #6 merges, then we can do step 2 above as a separate PR.

**Comment by gfinlay** [comment]
P.S. I have copied, added and committed the 4 .cfg files CANBUS.cfg, GPIO.cfg, SX150.cfg and USB_CADGET.cfg from the rzv2l mistysom_io branch  to your meta-mistysom PR #11 in the move-mw-fragments branch.

**Review by mistyron — APPROVED** [review]
LGTM

**Pull request merged**
